---
title: "Reproducibility Workshop Nihon にほん 2023"
author: 
  - "Lars Vilhuber"
  - "Chishio Furukawa"
date: September 2023
output: 
  ioslides_presentation:
    incremental: false
    self-included: true
    widescreen: true
---



# Before we start

## Languages

- All slides are in English
- Japanese language support will be onsite.

## Code of Conduct

- see [full Code of Conduct](https://github.com/labordynamicsinstitute/replicability-training/blob/master/LDI-Replication-Lab-Code-of-Conduct.md)

> We are dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity. By participating in this team, participants accept to abide by LDI ReplicationLab's Code of Conduct and accept the procedures by which any Code of Conduct incidents are resolved. Any form of behaviour to exclude, intimidate, or cause discomfort is a violation of the Code of Conduct. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all platforms and events:

- Use welcoming and inclusive language
-  Be respectful of different viewpoints and experiences
-  Gracefully accept constructive criticism
-  Focus on what is best for the community
-  Show courtesy and respect towards other community members

If you believe someone is violating the Code of Conduct, we ask that you report it to us.


# Next up: Real introduction

[Introduction](00-agenda.html)

